package com.rui.dao.cargo;

import com.rui.domain.cargo.Contract;
import com.rui.domain.cargo.ContractExample;
import java.util.List;

public interface ContractDao {

    int deleteByPrimaryKey(String id);

    int insert(Contract record);

    int insertSelective(Contract record);

    List<Contract> selectByExample(ContractExample example);

    Contract selectByPrimaryKey(String id);

    int updateByPrimaryKeySelective(Contract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_contract
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Contract record);
}