package com.rui.domain.cargo;

import java.io.Serializable;
import java.math.BigDecimal;

public class ExtCproduct implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_ext_cproduct.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_ext_cproduct.contract_product_id
     *
     * @mbg.generated
     */
    private String contractProductId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_ext_cproduct.contract_id
     *
     * @mbg.generated
     */
    private String contractId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_ext_cproduct.factory_id
     *
     * @mbg.generated
     */
    private String factoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_ext_cproduct.factory_name
     *
     * @mbg.generated
     */
    private String factoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_ext_cproduct.product_no
     *
     * @mbg.generated
     */
    private String productNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_ext_cproduct.product_image
     *
     * @mbg.generated
     */
    private String productImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_ext_cproduct.product_desc
     *
     * @mbg.generated
     */
    private String productDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_ext_cproduct.packing_unit
     *
     * @mbg.generated
     */
    private String packingUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_ext_cproduct.cnumber
     *
     * @mbg.generated
     */
    private Long cnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_ext_cproduct.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_ext_cproduct.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_ext_cproduct.order_no
     *
     * @mbg.generated
     */
    private Long orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_ext_cproduct.company_id
     *
     * @mbg.generated
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_ext_cproduct.company_name
     *
     * @mbg.generated
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_ext_cproduct.product_request
     *
     * @mbg.generated
     */
    private String productRequest;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_ext_cproduct.id
     *
     * @return the value of co_ext_cproduct.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_ext_cproduct.id
     *
     * @param id the value for co_ext_cproduct.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_ext_cproduct.contract_product_id
     *
     * @return the value of co_ext_cproduct.contract_product_id
     *
     * @mbg.generated
     */
    public String getContractProductId() {
        return contractProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_ext_cproduct.contract_product_id
     *
     * @param contractProductId the value for co_ext_cproduct.contract_product_id
     *
     * @mbg.generated
     */
    public void setContractProductId(String contractProductId) {
        this.contractProductId = contractProductId == null ? null : contractProductId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_ext_cproduct.contract_id
     *
     * @return the value of co_ext_cproduct.contract_id
     *
     * @mbg.generated
     */
    public String getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_ext_cproduct.contract_id
     *
     * @param contractId the value for co_ext_cproduct.contract_id
     *
     * @mbg.generated
     */
    public void setContractId(String contractId) {
        this.contractId = contractId == null ? null : contractId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_ext_cproduct.factory_id
     *
     * @return the value of co_ext_cproduct.factory_id
     *
     * @mbg.generated
     */
    public String getFactoryId() {
        return factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_ext_cproduct.factory_id
     *
     * @param factoryId the value for co_ext_cproduct.factory_id
     *
     * @mbg.generated
     */
    public void setFactoryId(String factoryId) {
        this.factoryId = factoryId == null ? null : factoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_ext_cproduct.factory_name
     *
     * @return the value of co_ext_cproduct.factory_name
     *
     * @mbg.generated
     */
    public String getFactoryName() {
        return factoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_ext_cproduct.factory_name
     *
     * @param factoryName the value for co_ext_cproduct.factory_name
     *
     * @mbg.generated
     */
    public void setFactoryName(String factoryName) {
        this.factoryName = factoryName == null ? null : factoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_ext_cproduct.product_no
     *
     * @return the value of co_ext_cproduct.product_no
     *
     * @mbg.generated
     */
    public String getProductNo() {
        return productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_ext_cproduct.product_no
     *
     * @param productNo the value for co_ext_cproduct.product_no
     *
     * @mbg.generated
     */
    public void setProductNo(String productNo) {
        this.productNo = productNo == null ? null : productNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_ext_cproduct.product_image
     *
     * @return the value of co_ext_cproduct.product_image
     *
     * @mbg.generated
     */
    public String getProductImage() {
        return productImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_ext_cproduct.product_image
     *
     * @param productImage the value for co_ext_cproduct.product_image
     *
     * @mbg.generated
     */
    public void setProductImage(String productImage) {
        this.productImage = productImage == null ? null : productImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_ext_cproduct.product_desc
     *
     * @return the value of co_ext_cproduct.product_desc
     *
     * @mbg.generated
     */
    public String getProductDesc() {
        return productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_ext_cproduct.product_desc
     *
     * @param productDesc the value for co_ext_cproduct.product_desc
     *
     * @mbg.generated
     */
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc == null ? null : productDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_ext_cproduct.packing_unit
     *
     * @return the value of co_ext_cproduct.packing_unit
     *
     * @mbg.generated
     */
    public String getPackingUnit() {
        return packingUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_ext_cproduct.packing_unit
     *
     * @param packingUnit the value for co_ext_cproduct.packing_unit
     *
     * @mbg.generated
     */
    public void setPackingUnit(String packingUnit) {
        this.packingUnit = packingUnit == null ? null : packingUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_ext_cproduct.cnumber
     *
     * @return the value of co_ext_cproduct.cnumber
     *
     * @mbg.generated
     */
    public Long getCnumber() {
        return cnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_ext_cproduct.cnumber
     *
     * @param cnumber the value for co_ext_cproduct.cnumber
     *
     * @mbg.generated
     */
    public void setCnumber(Long cnumber) {
        this.cnumber = cnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_ext_cproduct.price
     *
     * @return the value of co_ext_cproduct.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_ext_cproduct.price
     *
     * @param price the value for co_ext_cproduct.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_ext_cproduct.amount
     *
     * @return the value of co_ext_cproduct.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_ext_cproduct.amount
     *
     * @param amount the value for co_ext_cproduct.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_ext_cproduct.order_no
     *
     * @return the value of co_ext_cproduct.order_no
     *
     * @mbg.generated
     */
    public Long getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_ext_cproduct.order_no
     *
     * @param orderNo the value for co_ext_cproduct.order_no
     *
     * @mbg.generated
     */
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_ext_cproduct.company_id
     *
     * @return the value of co_ext_cproduct.company_id
     *
     * @mbg.generated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_ext_cproduct.company_id
     *
     * @param companyId the value for co_ext_cproduct.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_ext_cproduct.company_name
     *
     * @return the value of co_ext_cproduct.company_name
     *
     * @mbg.generated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_ext_cproduct.company_name
     *
     * @param companyName the value for co_ext_cproduct.company_name
     *
     * @mbg.generated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_ext_cproduct.product_request
     *
     * @return the value of co_ext_cproduct.product_request
     *
     * @mbg.generated
     */
    public String getProductRequest() {
        return productRequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_ext_cproduct.product_request
     *
     * @param productRequest the value for co_ext_cproduct.product_request
     *
     * @mbg.generated
     */
    public void setProductRequest(String productRequest) {
        this.productRequest = productRequest == null ? null : productRequest.trim();
    }
}